#!/usr/bin/env python
"""Stage 4 training: varied-IC ensemble MCB policy (state-dependent controller).

Trains the MCB policy across multiple spin-up-snapshot initial conditions
(generated by run_stage4_generate_ics.py), averaging BPTT gradients across
ICs each epoch. Held-out ICs are evaluated forward-only and logged.

Features use CoupledFeatureConfig(include_absolute_sst=True) (13 dims): the
two absolute-SST features distinguish ICs at interval 0, where paired
anomalies are provably zero. Warm start from the Stage 3 checkpoint expands
the 11-feature first layer with zero rows (bit-identical initial behavior).

Usage:
    python run_stage4_training.py --epochs 150 \
        --init-checkpoint mcb_experiments/stage3_60d/coupled_trained_policy.pkl \
        --ic-dir mcb_experiments/stage4/ics --output-dir mcb_experiments/stage4
"""

import argparse
import json
import pickle
from pathlib import Path

import jax
import jax.numpy as jnp
import jax_datetime as jdt

from jcm.mcb import (
    CoupledBaselineTrajectory,
    CoupledControllerConfig,
    CoupledFeatureConfig,
    CoupledLossWeights,
    MCBPolicyMLP,
    expand_policy_input,
    get_coupled_feature_dim,
    load_carry,
)
from jcm.mcb.coupled_train import (
    create_coupled_grad_fn,
    train_coupled_policy_ensemble,
)
from jcm.mcb.train import TrainingConfig, load_checkpoint, save_checkpoint

from run_coupled_training import setup_coupled_model, warm_start_params

WORKFLOW = ["coupling", "atm", "ocn"]
START_DATE = "2000-01-01"


def parse_args():
    parser = argparse.ArgumentParser(description="Stage 4 ensemble training")
    parser.add_argument("--ic-dir", type=str,
                        default="mcb_experiments/stage4/ics",
                        help="Directory with manifest.json + IC pickles")
    parser.add_argument("--output-dir", type=str,
                        default="mcb_experiments/stage4")
    parser.add_argument("--epochs", type=int, default=150)
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument("--days", type=int, default=60,
                        help="Rollout horizon per IC (days)")
    parser.add_argument("--control-interval", type=int, default=30,
                        help="Days between policy applications")
    parser.add_argument("--target-cooling", type=float, default=-0.1)
    parser.add_argument("--heldout-interval", type=int, default=10,
                        help="Epochs between held-out evaluations")
    parser.add_argument("--init-checkpoint", type=str,
                        default="mcb_experiments/stage3_60d/coupled_trained_policy.pkl",
                        help="Stage 3 checkpoint (11 features) to warm-start "
                             "from; expanded to 13 features with zero rows")
    parser.add_argument("--warm-start-stage1", type=str, default=None,
                        help="Fallback: Stage 1 pattern pickle; sets the "
                             "output bias to the optimized pattern instead "
                             "of using --init-checkpoint")
    return parser.parse_args()


def load_baseline_trajectory(path, days):
    """Load a pickled baseline dict as a CoupledBaselineTrajectory."""
    with open(path, "rb") as f:
        d = pickle.load(f)
    assert d["sst"].shape[0] >= days + 1, (
        f"Baseline {path} covers {d['sst'].shape[0] - 1} days, need {days}"
    )
    return CoupledBaselineTrajectory(
        sst=jnp.asarray(d["sst"][:days + 1]),
        surface_temperature=jnp.asarray(d["surface_temperature"][:days + 1]),
        precipitation=jnp.asarray(d["precipitation"][:days + 1]),
        heat_flux=jnp.asarray(d["heat_flux"][:days + 1]),
    )


def load_ics(ic_dir, days, template_carry):
    """Load manifest, carries and baselines; return (manifest, train, heldout)."""
    ic_dir = Path(ic_dir)
    with open(ic_dir / "manifest.json") as f:
        manifest = json.load(f)

    assert manifest["start_date"] == START_DATE, (
        f"Manifest start_date {manifest['start_date']} != {START_DATE}"
    )
    assert manifest["horizon"] >= days, (
        f"Manifest horizon {manifest['horizon']} < requested days {days}"
    )

    train, heldout = [], []
    for entry in manifest["ics"]:
        carry = load_carry(str(ic_dir / entry["carry_file"]), template_carry)
        baseline = load_baseline_trajectory(
            ic_dir / entry["baseline_file"], days
        )
        target = train if entry["split"] == "train" else heldout
        target.append((entry, carry, baseline))

    return manifest, train, heldout


def main():
    args = parse_args()
    assert args.days % args.control_interval == 0

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("STAGE 4 TRAINING: varied-IC ensemble MCB policy")
    print("=" * 70)
    print(f"JAX devices: {jax.devices()}")

    start_datetime = jdt.to_datetime(START_DATE)
    coupling_timestep = jdt.to_timedelta(1, "day")
    coupler, coords, terrain, atm_model = setup_coupled_model(
        start_datetime, coupling_timestep
    )
    template_carry = coupler.initialize()

    print(f"\nLoading ICs from {args.ic_dir}...")
    manifest, train_ics, heldout_ics = load_ics(
        args.ic_dir, args.days, template_carry
    )
    print(f"  {len(train_ics)} train ICs "
          f"(spin-up days {[e['spinup_days'] for e, _, _ in train_ics]})")
    print(f"  {len(heldout_ics)} held-out ICs "
          f"(spin-up days {[e['spinup_days'] for e, _, _ in heldout_ics]})")

    train_carries = [c for _, c, _ in train_ics]
    train_baselines = [b for _, _, b in train_ics]
    heldout_carries = [c for _, c, _ in heldout_ics]
    heldout_baselines = [b for _, _, b in heldout_ics]

    # 13-feature config: absolute-SST features distinguish ICs at interval 0
    feature_config = CoupledFeatureConfig(include_absolute_sst=True)
    feature_dim = get_coupled_feature_dim(feature_config)
    base_dim = get_coupled_feature_dim(CoupledFeatureConfig())
    print(f"\nFeature dim: {feature_dim} (base {base_dim} + absolute SST)")

    policy = MCBPolicyMLP(
        output_shape=coords.horizontal.nodal_shape,
        hidden_dims=(256, 256),
        max_perturbation=0.15,
    )

    controller_config = CoupledControllerConfig(
        control_interval_steps=args.control_interval,
        total_steps=args.days,
        target_cooling=args.target_cooling,
        loss_weights=CoupledLossWeights(
            sst_cooling=1.0,
            sst_uniformity=0.1,
            amazon=0.0,
            sahel=0.0,
            tropics=0.0,
            regularization=0.001,
            smoothness=0.001,
        ),
        feature_config=feature_config,
        max_perturbation=0.15,
        use_checkpointing=True,
    )

    training_config = TrainingConfig(
        num_epochs=args.epochs,
        learning_rate=args.learning_rate,
        lr_schedule='constant',
        optimizer='adam',
        grad_clip_norm=1.0,
        log_interval=1,
        early_stopping_patience=20,
    )

    # Warm start: Stage 1 pattern (bias trick) or Stage 3 checkpoint
    # (expanded 11 -> 13 with zero rows, bit-identical initial behavior)
    initial_params = None
    init_source = "random"
    if args.warm_start_stage1:
        initial_params = warm_start_params(
            policy, feature_dim, args.warm_start_stage1
        )
        init_source = f"stage1:{args.warm_start_stage1}"
    elif Path(args.init_checkpoint).exists():
        ckpt_params, ckpt_meta = load_checkpoint(args.init_checkpoint)
        old_dim = ckpt_params['params']['hidden_0']['kernel'].shape[0]
        print(f"  Expanding checkpoint input dim {old_dim} -> {feature_dim}")
        initial_params = expand_policy_input(ckpt_params, old_dim, feature_dim)
        init_source = f"stage3:{args.init_checkpoint}"
    else:
        print(f"  WARNING: init checkpoint {args.init_checkpoint} not found; "
              f"using random initialization")

    # Pre-flight gradient sanity check on IC 0
    print("\nPre-flight gradient check on IC 0...")
    grad_fn = create_coupled_grad_fn(
        coupler=coupler,
        workflow=WORKFLOW,
        policy_fn=policy.apply,
        coords=coords,
        ocean_mask=1.0 - terrain.fmask,
        controller_config=controller_config,
    )
    check_params = initial_params
    if check_params is None:
        check_params = policy.init(
            jax.random.PRNGKey(training_config.random_seed),
            jnp.zeros(feature_dim),
        )
    loss, grads = grad_fn(check_params, train_carries[0], train_baselines[0])
    grad_leaves = jax.tree.leaves(grads)
    grad_norm = float(jnp.linalg.norm(
        jnp.concatenate([g.ravel() for g in grad_leaves])
    ))
    has_nans = any(bool(jnp.any(jnp.isnan(g))) for g in grad_leaves)
    all_zeros = all(bool(jnp.allclose(g, 0.0)) for g in grad_leaves)
    print(f"  loss = {float(loss):.6f}, grad norm = {grad_norm:.4f}")
    if has_nans or all_zeros:
        print(f"  FAILED: has_nans={has_nans}, all_zeros={all_zeros}")
        return

    print("\n" + "=" * 70)
    print("Starting ensemble training...")
    print("=" * 70)

    best_params, history = train_coupled_policy_ensemble(
        coupler=coupler,
        workflow=WORKFLOW,
        policy=policy,
        coords=coords,
        terrain_fmask=terrain.fmask,
        train_carries=train_carries,
        train_baselines=train_baselines,
        heldout_carries=heldout_carries,
        heldout_baselines=heldout_baselines,
        training_config=training_config,
        controller_config=controller_config,
        initial_params=initial_params,
        heldout_interval=args.heldout_interval,
    )

    print("\nSaving results...")
    checkpoint_path = output_dir / "stage4_trained_policy.pkl"
    save_checkpoint(
        best_params,
        str(checkpoint_path),
        metadata={
            'epochs': history['epochs_completed'],
            'best_loss': history['best_loss'],
            'target_cooling': args.target_cooling,
            'mode': 'coupled-ensemble',
            'feature_dim': feature_dim,
            'include_absolute_sst': True,
            'init_source': init_source,
            'train_ics': [e['spinup_days'] for e, _, _ in train_ics],
            'heldout_ics': [e['spinup_days'] for e, _, _ in heldout_ics],
            'days': args.days,
            'control_interval': args.control_interval,
        }
    )

    history_path = output_dir / "stage4_training_history.pkl"
    with open(history_path, 'wb') as f:
        pickle.dump(history, f)
    print(f"Saved training history to {history_path}")

    print("\n" + "=" * 70)
    print("Training Complete!")
    print("=" * 70)
    print(f"  Best mean loss: {history['best_loss']:.6f}")
    print(f"  Final mean loss: {history['final_loss']:.6f}")
    print(f"  Epochs: {history['epochs_completed']}")
    if history['heldout_loss_history']:
        epoch, losses = history['heldout_loss_history'][-1]
        print(f"  Last held-out eval (epoch {epoch}): "
              f"mean {sum(losses) / len(losses):.6f} {losses}")
    print(f"\nOutput saved to: {output_dir}")


if __name__ == "__main__":
    main()
